### ISSUE TITLE
Possible issue with query when navigating to related entities

### ISSUE THREAD

**Issue by gra-moore** [mimiro-io/datahub#183]
when using the via-flag as something other than "*" the mim-cli returns:
panic: runtime error: slice bounds out of range [1:0]

goroutine 1 [running]:
github.com/mimiro-io/datahub-cli/internal/command.glob..func10(0x26baf60?, {0xc00018f4f0, 0x0, 0x5})
	/Users/ahlberg/mimiro-datahub/datahub-cli/internal/command/query.go:83 +0x4d3
github.com/spf13/cobra.(*Command).execute(0x26baf60, {0xc00018f4a0, 0x5, 0x5})
	/Users/ahlberg/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x26b9660)
	/Users/ahlberg/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x39c
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/ahlberg/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/mimiro-io/datahub-cli.Execute()
	/Users/ahlberg/mimiro-datahub/datahub-cli/root.go:51 +0x25
main.main()
	/Users/ahlberg/mimiro-datahub/datahub-cli/cmd/cli/main.go:23 +0x17

example from dev-hub:
DOESNT WORK
mim query --entity "ns17:10" --via="http://data.mimiro.io/eana360/activitylog/animals/" --inverse=false --pretty

DOES WORK
mim query --entity "ns17:10" --via="*" --inverse=false --pretty

**Comment by gra-moore** [comment]
I notice that the via property is with a trailing slash. Wonder if this is the reason.

**Comment by gra-moore** [comment]
I have had a look at this. The datahub is working as expected but the mim cli is not rendering the result correctly. It is assuming a normal entity stream response and this is incorrect. The result is a list with context followed by a list of result rows. Each result row is a list of entity, predicate and then related entity.

**Comment by gra-moore** [comment]
Closing as issue added to mim-cli. https://github.com/mimiro-io/datahub-cli/issues/153
